// Editorial content is rendered as HTML at server startup, with one address per language.
const repo = 'https://github.com/theslumdogemillionaire/twichat'
export const PROJECT_URL = repo
export const CONTENT = [
  {
    key: 'mac', slugs: { fr: 'installer-twichat-macos', en: 'install-twichat-macos' },
    fr: { title: 'Installer Twichat sur Mac : Intel et Apple Silicon', description: 'Téléchargez Twichat pour macOS. Installation du DMG universel sur Mac Intel et Apple Silicon, première ouverture et mises à jour.', intro: 'Twichat est un client Twitch gratuit pour Mac. Le même fichier DMG contient les versions Intel et Apple Silicon : vous n’avez pas à choisir votre processeur.', sections: [
      ['installation', 'Installer l’application', '<ol><li>Téléchargez le fichier DMG depuis le lien ci-dessous.</li><li>Ouvrez le DMG, puis copiez Twichat dans le dossier Applications.</li><li>Lancez Twichat depuis Applications. Vous pouvez ensuite éjecter le disque d’installation.</li><li>Choisissez le mode anonyme pour commencer à lire les chats, ou connectez votre compte Twitch pour écrire.</li></ol>'],
      ['premiere-ouverture', 'Si macOS bloque la première ouverture', '<p>Les versions actuelles de Twichat ne sont pas signées ni notariées par Apple. macOS peut donc refuser leur ouverture. Vérifiez que le fichier vient de la publication officielle avant de décider de l’autoriser.</p><p>Après une première tentative, l’option « Ouvrir quand même » peut apparaître dans Réglages Système → Confidentialité et sécurité. Consultez la <a href="https://support.apple.com/fr-fr/102445">procédure Apple et la signification des alertes</a>. Ne désactivez pas globalement les protections du Mac.</p>'],
      ['mises-a-jour', 'Mettre à jour et signaler un problème', '<p>Sur Mac, Twichat signale les nouvelles versions et ouvre leur page de téléchargement. Installez le nouveau DMG pour remplacer l’application. Vos préférences restent dans votre dossier utilisateur.</p><p>Pour un problème d’ouverture, indiquez votre version de macOS, votre processeur et le message exact dans un signalement GitHub. Les paquets sont universels ; cela ne garantit pas leur fonctionnement sur toutes les anciennes versions de macOS.</p>']
    ] },
    en: { title: 'Install Twichat on Mac: Intel and Apple Silicon', description: 'Download Twichat for macOS. Install the universal DMG on Intel and Apple Silicon Macs, handle the first launch and get updates.', intro: 'Twichat is a free Twitch client for Mac. One universal DMG includes both Intel and Apple Silicon builds, so there is no processor version to choose.', sections: [
      ['installation', 'Install the application', '<ol><li>Download the DMG using the link below.</li><li>Open the DMG and copy Twichat to Applications.</li><li>Launch Twichat from Applications. You can then eject the installation disk.</li><li>Use anonymous mode to start reading chats, or connect your Twitch account to send messages.</li></ol>'],
      ['first-launch', 'If macOS blocks the first launch', '<p>Current Twichat builds are not signed or notarized by Apple, so macOS may block them. Check that your download comes from the official release before deciding to allow it.</p><p>After attempting to launch it, “Open Anyway” may appear in System Settings → Privacy &amp; Security. Read <a href="https://support.apple.com/en-gb/102445">Apple’s instructions and explanation of the alerts</a>. Do not disable your Mac’s protections globally.</p>'],
      ['updates', 'Updates and troubleshooting', '<p>On Mac, Twichat announces new versions and opens their download page. Install the new DMG to replace the app. Your preferences remain in your user directory.</p><p>For launch issues, include your macOS version, processor and exact error in a GitHub report. Universal packaging does not mean every older macOS version is supported.</p>']
    ] }
  },
  {
    key: 'windows', slugs: { fr: 'installer-twichat-windows', en: 'install-twichat-windows' },
    fr: { title: 'Installer Twichat sur Windows : le client Twitch gratuit', description: 'Installez Twichat sur Windows avec le programme EXE x64. Découvrez la connexion Twitch, les mises à jour et les informations utiles en cas de problème.', intro: 'Twichat permet de lire et de rejoindre les chats Twitch dans une application Windows. L’installateur proposé est un fichier EXE pour les PC x64.', sections: [
      ['installation', 'Télécharger et installer', '<ol><li>Téléchargez l’installateur Windows officiel.</li><li>Ouvrez le fichier EXE et suivez les étapes de l’assistant.</li><li>Lancez Twichat, puis choisissez le mode anonyme ou la connexion Twitch.</li><li>Ajoutez une chaîne pour afficher son chat. Un compte Twitch est nécessaire pour envoyer des messages.</li></ol><p>Les versions publiées ciblent x64. Il n’existe pas actuellement de paquet Windows ARM natif.</p>'],
      ['connexion', 'Connexion et première utilisation', '<p>La connexion s’ouvre dans votre navigateur sur Twitch. Après autorisation, acceptez le retour dans Twichat. Votre mot de passe est saisi sur Twitch, pas dans l’application.</p><p>Si le navigateur ne revient pas à l’application, vérifiez que Twichat est installé, puis relancez la connexion depuis l’application. Ne communiquez jamais un jeton de connexion dans un signalement public.</p>'],
      ['mises-a-jour', 'Mises à jour et dépannage', '<p>Le programme Windows peut télécharger une mise à jour en arrière-plan et proposer un redémarrage pour l’appliquer. Le programme d’installation reste disponible sur la page des versions.</p><p>Si Windows affiche une alerte de sécurité, vérifiez la provenance du fichier et le détail de l’alerte avant de continuer. Pour demander de l’aide, précisez votre version de Windows, le processeur et le message affiché. Aucun outil de développement n’est nécessaire pour utiliser l’installateur.</p>']
    ] },
    en: { title: 'Install Twichat on Windows: a free Twitch chat client', description: 'Install Twichat on Windows with the x64 EXE installer. Learn about Twitch sign-in, updates and what to include in a troubleshooting report.', intro: 'Twichat puts Twitch chats in a dedicated Windows application. The download is an EXE installer for x64 PCs.', sections: [
      ['installation', 'Download and install', '<ol><li>Download the official Windows installer.</li><li>Open the EXE file and follow the setup steps.</li><li>Launch Twichat and choose anonymous mode or Twitch sign-in.</li><li>Add a channel to see its chat. Sending messages requires a Twitch account.</li></ol><p>Published Windows builds target x64. There is currently no native Windows ARM package.</p>'],
      ['sign-in', 'Sign in and get started', '<p>Sign-in opens Twitch in your browser. After authorizing access, allow the browser to return to Twichat. Your password is entered on Twitch, not in the application.</p><p>If the browser cannot return to the app, check that Twichat is installed and start sign-in again from the application. Never include a sign-in token in a public issue.</p>'],
      ['updates', 'Updates and troubleshooting', '<p>The Windows app can download an update in the background and offer a restart to apply it. The installer is also available from the releases page.</p><p>If Windows displays a security alert, check the file’s source and read the alert before continuing. Include your Windows version, processor and exact error when asking for help. You do not need development tools to use the installer.</p>']
    ] }
  },
  {
    key: 'linux', slugs: { fr: 'installer-twichat-linux', en: 'install-twichat-linux' },
    fr: { title: 'Installer Twichat sur Linux : AppImage, deb ou rpm', description: 'Choisissez le bon paquet Twichat sur Linux : AppImage, deb ou rpm, pour x64 ou ARM64. Installation, mises à jour et dépannage.', intro: 'Twichat est disponible sur Linux en AppImage, deb et rpm, avec un paquet x64 et un paquet ARM64 pour chaque format. Choisissez d’abord votre architecture, puis le format adapté à votre distribution.', sections: [
      ['paquet', 'Quel format choisir ?', '<ul><li><strong>AppImage :</strong> un fichier autonome à rendre exécutable ; Twichat peut mettre à jour cette version.</li><li><strong>deb :</strong> un paquet pour les distributions utilisant les paquets Debian, notamment Debian et Ubuntu.</li><li><strong>rpm :</strong> un paquet pour les distributions utilisant RPM, notamment Fedora.</li></ul><p>La commande <code>uname -m</code> indique généralement <code>x86_64</code> pour x64, ou <code>aarch64</code> pour ARM64. Dans les noms deb, x64 s’écrit <code>amd64</code>.</p>'],
      ['installation', 'Installer le paquet choisi', '<p>Pour AppImage, ouvrez les propriétés du fichier téléchargé et autorisez son exécution, puis lancez-le. Si votre distribution signale une dépendance FUSE manquante, consultez sa documentation ou utilisez le paquet deb ou rpm adapté.</p><p>Pour deb ou rpm, ouvrez le fichier dans le gestionnaire de logiciels de votre distribution. Il gère l’installation et les dépendances. Ces téléchargements sont des paquets individuels, pas un dépôt de mises à jour.</p>'],
      ['compte', 'Compte Twitch et stockage sécurisé', '<p>Vous pouvez commencer en mode anonyme. Pour conserver un compte connecté, l’application utilise le stockage sécurisé disponible sur le système. Si Twichat indique que ce stockage est indisponible, vérifiez le service de trousseau de votre environnement de bureau.</p><p>Lors d’un signalement, indiquez la distribution, sa version, l’architecture, le format choisi et l’erreur exacte.</p>'],
      ['mises-a-jour', 'Mettre à jour', '<p>La version AppImage peut être remplacée par le mécanisme de mise à jour de Twichat. Pour deb et rpm, téléchargez le nouveau paquet puis installez-le avec le gestionnaire de votre distribution.</p>']
    ] },
    en: { title: 'Install Twichat on Linux: AppImage, deb or rpm', description: 'Choose a Twichat Linux package: AppImage, deb or rpm for x64 or ARM64. Installation, secure account storage, updates and troubleshooting.', intro: 'Twichat is available on Linux as AppImage, deb and rpm, with x64 and ARM64 builds for each format. Choose your architecture first, then the package format used by your distribution.', sections: [
      ['package', 'Which package should you choose?', '<ul><li><strong>AppImage:</strong> a standalone file you make executable; Twichat can update this build.</li><li><strong>deb:</strong> for distributions using Debian packages, including Debian and Ubuntu.</li><li><strong>rpm:</strong> for distributions using RPM packages, including Fedora.</li></ul><p><code>uname -m</code> usually reports <code>x86_64</code> for x64 or <code>aarch64</code> for ARM64. Debian package names use <code>amd64</code> for x64.</p>'],
      ['installation', 'Install your chosen package', '<p>For AppImage, open the downloaded file’s properties, allow execution and launch it. If your distribution reports a missing FUSE dependency, consult its documentation or use the appropriate deb or rpm package.</p><p>For deb or rpm, open the file in your distribution’s software manager, which handles installation and dependencies. These are individual packages, not an update repository.</p>'],
      ['account', 'Twitch accounts and secure storage', '<p>You can start in anonymous mode. To remember a connected account, Twichat uses the secure storage available on your system. If the app reports that secure storage is unavailable, check your desktop environment’s keyring service.</p><p>When reporting an issue, include the distribution, version, architecture, package format and exact error.</p>'],
      ['updates', 'Keep the app updated', '<p>Twichat’s update mechanism can replace the AppImage build. For deb and rpm, download the new package and install it through your distribution’s package manager.</p>']
    ] }
  },
  {
    key: 'about', slugs: { fr: 'a-propos', en: 'about' },
    fr: { title: 'À propos de Twichat : projet, licence et contact', description: 'Qui développe Twichat ? Découvrez le projet indépendant, sa licence MIT, son code source et les moyens de contacter son auteur.', intro: 'Twichat est un client Twitch indépendant développé par The Slumdoge Millionaire. Il permet d’organiser le chat et la vidéo selon ses habitudes, dans une interface épurée et réactive. Les emotes sont intégrées, sans extension à installer.', sections: [
      ['projet', 'Un projet indépendant et gratuit', `<p>Twichat est distribué gratuitement sous <a href="${repo}/blob/main/LICENSE">licence MIT</a>. Son code et celui du serveur de connexion sont <a href="${repo}">consultables sur GitHub</a>. L’application est actuellement en alpha : des fonctions peuvent évoluer et des problèmes subsister.</p><p>Twichat n’est ni développé ni approuvé par Twitch. Twitch est une marque de Twitch Interactive, Inc.</p>`],
      ['contact', 'Aide, suggestions et contact', `<p>Pour un problème ou une idée, ouvrez un <a href="${repo}/issues">signalement GitHub</a> en précisant votre système et votre version de Twichat. Pour contacter l’auteur : <a href="mailto:root@theslumdogemillionaire.com">root@theslumdogemillionaire.com</a>.</p><p>Une faille de sécurité doit être signalée en privé, via <a href="${repo}/security/advisories/new">le formulaire de sécurité GitHub</a> ou par courriel. N’ajoutez pas de jeton Twitch à un message public.</p>`],
      ['versions', 'Suivre les changements', `<p>La <a href="${repo}/releases">liste des versions</a> présente les publications et leurs fichiers d’installation. Les téléchargements pour macOS, Windows et Linux proviennent de ces publications officielles.</p>`]
    ] },
    en: { title: 'About Twichat: project, license and contact', description: 'Who develops Twichat? Learn about the independent project, its MIT license, source code and how to contact its developer.', intro: 'Twichat is an independent Twitch client developed by The Slumdoge Millionaire. It lets you arrange chat and video to suit how you watch, in a clean, responsive interface. Emotes are built in, with no extensions to install.', sections: [
      ['project', 'An independent, free application', `<p>Twichat is free and released under the <a href="${repo}/blob/main/LICENSE">MIT license</a>. The app and sign-in server source code are <a href="${repo}">available on GitHub</a>. The application is currently in alpha: features may change and issues may remain.</p><p>Twichat is not developed or endorsed by Twitch. Twitch is a trademark of Twitch Interactive, Inc.</p>`],
      ['contact', 'Help, suggestions and contact', `<p>For a problem or idea, open a <a href="${repo}/issues">GitHub issue</a> and include your system and Twichat version. Contact the developer at <a href="mailto:root@theslumdogemillionaire.com">root@theslumdogemillionaire.com</a>.</p><p>Report security vulnerabilities privately through <a href="${repo}/security/advisories/new">GitHub’s security form</a> or email. Never put a Twitch token in a public report.</p>`],
      ['releases', 'Follow the changes', `<p>The <a href="${repo}/releases">releases page</a> lists publications and installers. Downloads for macOS, Windows and Linux come from these official releases.</p>`]
    ] }
  },
  {
    key: 'privacy', slugs: { fr: 'confidentialite', en: 'privacy' },
    fr: { title: 'Confidentialité : les données utilisées par Twichat', description: 'Données locales, jetons Twitch, connexion, fournisseurs d’emotes et hébergement du site : ce que Twichat stocke et transmet.', intro: 'Twichat conserve ses préférences et ses comptes sur votre ordinateur. L’application ne contient pas de télémétrie d’usage ni de rapporteur de plantages. Elle contacte les services nécessaires au chat, à la vidéo, aux emotes et aux mises à jour.', sections: [
      ['ordinateur', 'Sur votre ordinateur', '<p>Les préférences et les chaînes rejointes sont stockées dans <code>twichat.db</code>. Les identifiants de compte et les jetons se trouvent dans <code>accounts.json</code> ; les jetons sont chiffrés via le stockage sécurisé du système. Deux caches conservent des avatars de comptes et de chaînes.</p><p>Les 500 derniers messages de chaque chaîne restent en mémoire et ne constituent pas un historique enregistré sur disque. Fermer l’application les efface. Se déconnecter conserve le compte pour une connexion ultérieure.</p>'],
      ['connexion', 'Pendant la connexion Twitch', '<p>Votre mot de passe est saisi chez Twitch. Le serveur de connexion échange le code d’autorisation contre des jetons, conservés en mémoire derrière un ticket valable deux minutes. Le ticket est supprimé quand l’application le récupère. Le renouvellement d’un jeton passe également par ce serveur.</p><p>Les autorisations demandées couvrent la lecture et l’envoi dans le chat, la lecture des chaînes suivies et les chuchotements. Elles ne permettent pas de gérer vos abonnements. Vous pouvez révoquer l’accès depuis les connexions de votre compte Twitch.</p>'],
      ['services', 'Les services contactés', '<p>Twitch fournit le chat, les profils, les événements et la vidéo. 7TV, BetterTTV et FrankerFaceZ fournissent leurs emotes. Les images GIPHY sont chargées lorsqu’un message en contient et que leur affichage est activé. GitHub sert à vérifier et télécharger les mises à jour.</p><p>Ces fournisseurs reçoivent les requêtes nécessaires, notamment votre adresse IP. Leurs règles de confidentialité s’appliquent à ces échanges.</p>'],
      ['site', 'Sur ce site', '<p>Le code du site n’ajoute ni outil d’analytics ni cookie. Il mémorise dans le stockage local du navigateur votre choix de thème et de langue. Les polices et les images sont servies par ce domaine.</p><p>Le site public passe par Cloudflare et un serveur HTTP : ces intermédiaires traitent les informations nécessaires aux connexions, dont l’adresse IP. L’absence d’analytics dans l’application ne signifie pas l’absence de traitement technique par l’hébergeur. <a href="https://www.cloudflare.com/privacypolicy/">Politique de confidentialité de Cloudflare</a>.</p>'],
      ['effacer', 'Effacer les données et nous contacter', `<p>Quittez Twichat avant de supprimer son dossier de données : <code>~/Library/Application Support/Twichat</code> sur Mac, <code>%APPDATA%\\Twichat</code> sur Windows ou <code>~/.config/Twichat</code> sur Linux. Cela efface les réglages, comptes enregistrés et caches locaux. La révocation chez Twitch est une action distincte.</p><p>Pour le site, effacez les données de ce domaine dans votre navigateur. Pour une question : <a href="mailto:root@theslumdogemillionaire.com">root@theslumdogemillionaire.com</a>. Le <a href="${repo}">code source</a> permet d’examiner ces mécanismes.</p>`]
    ] },
    en: { title: 'Privacy: what data Twichat uses', description: 'Local data, Twitch tokens, sign-in, emote providers and site hosting: what Twichat stores and sends.', intro: 'Twichat keeps preferences and accounts on your computer. The application has no usage telemetry or crash reporter. It contacts the services needed for chat, video, emotes and updates.', sections: [
      ['computer', 'On your computer', '<p>Preferences and joined channels are stored in <code>twichat.db</code>. Account names and tokens are kept in <code>accounts.json</code>; tokens are encrypted through the operating system’s secure storage. Two caches keep account and channel avatars.</p><p>The last 500 messages per channel stay in memory, not in a chat log on disk. Closing the app clears them. Signing out keeps the account available for a later sign-in.</p>'],
      ['sign-in', 'During Twitch sign-in', '<p>You enter your password on Twitch. The sign-in server exchanges the authorization code for tokens held in memory behind a ticket valid for two minutes. The ticket is deleted when the app claims it. Token renewal also passes through this server.</p><p>Requested permissions cover reading and sending chat messages, reading followed channels and managing whispers. They do not allow the app to manage your subscriptions. You can revoke access from your Twitch account’s connections settings.</p>'],
      ['services', 'Services the app contacts', '<p>Twitch provides chat, profiles, events and video. 7TV, BetterTTV and FrankerFaceZ provide emotes. GIPHY images load when a message contains one and their display is enabled. GitHub is used to check for and download updates.</p><p>These providers receive the requests needed to deliver their services, including your IP address. Their own privacy policies apply to those exchanges.</p>'],
      ['website', 'On this website', '<p>The site code adds no analytics tool or cookie. Your theme and language choices are saved in your browser’s local storage. Fonts and images are served from this domain.</p><p>The public site uses Cloudflare and an HTTP server. These intermediaries process connection information, including IP addresses. No in-app analytics does not mean the hosting provider processes no technical data. <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare’s privacy policy</a>.</p>'],
      ['erase', 'Delete data and contact us', `<p>Quit Twichat before deleting its data directory: <code>~/Library/Application Support/Twichat</code> on Mac, <code>%APPDATA%\\Twichat</code> on Windows or <code>~/.config/Twichat</code> on Linux. This removes local settings, saved accounts and caches. Revoking access on Twitch is a separate action.</p><p>For this site, clear the domain’s data in your browser. Questions: <a href="mailto:root@theslumdogemillionaire.com">root@theslumdogemillionaire.com</a>. You can inspect these mechanisms in the <a href="${repo}">source code</a>.</p>`]
    ] }
  },
  {
    key: 'guide', slugs: { fr: 'chat-twitch-plein-ecran', en: 'twitch-chat-full-screen' }, article: true,
    fr: { title: 'Comment afficher le chat Twitch en plein écran ?', description: 'Chat Twitch en plein écran, fenêtre séparée ou second écran : choisissez la méthode adaptée pour lire les messages sans perdre le direct.', intro: 'Pour agrandir le chat Twitch sur ordinateur, ouvrez-le dans une fenêtre séparée puis agrandissez cette fenêtre. Pour garder aussi la vidéo, utilisez le mode studio de Twitch, deux fenêtres côte à côte ou un client de bureau comme Twichat.', sections: [
      ['choisir', 'Quelle méthode correspond à votre écran ?', '<div class="reading-table"><table><thead><tr><th>Votre besoin</th><th>La méthode</th><th>À savoir</th></tr></thead><tbody><tr><td>Lire uniquement le chat en grand</td><td>Chat dans une fenêtre séparée</td><td>La vidéo reste dans la fenêtre Twitch.</td></tr><tr><td>Garder vidéo et chat sur un écran</td><td>Mode studio ou fenêtres côte à côte</td><td>Le plein écran du lecteur vidéo ne conserve pas le chat à côté.</td></tr><tr><td>Mettre le chat sur un second écran</td><td>Déplacer la fenêtre du chat</td><td>Vous pouvez laisser la vidéo sur l’écran principal.</td></tr><tr><td>Passer entre plusieurs chaînes</td><td>Client de bureau Twichat</td><td>Plusieurs chats restent ouverts, avec un seul flux vidéo actif.</td></tr></tbody></table></div>'],
      ['fenetre', '1. Ouvrir le chat Twitch dans une fenêtre séparée', '<ol><li>Ouvrez une chaîne sur le site Twitch depuis un navigateur d’ordinateur.</li><li>Dans les réglages du chat, cherchez l’option qui permet d’ouvrir le chat dans une fenêtre séparée. Son libellé peut varier selon la langue de Twitch.</li><li>Agrandissez cette fenêtre, ou déplacez-la vers un second écran.</li><li>Pour lire uniquement les messages, gardez cette fenêtre au premier plan. La vidéo reste dans la page de la chaîne.</li></ol><p>Vous pouvez aussi utiliser le mode plein écran de votre navigateur sur la fenêtre du chat. Il s’agit du plein écran du navigateur, pas du bouton plein écran du lecteur vidéo.</p><p>Twitch décrit la séparation du chat dans sa <a href="https://help.twitch.tv/s/article/a-tour-of-your-channel-page?language=fr">présentation de la page de chaîne</a>.</p>'],
      ['video', '2. Garder le chat à côté de la vidéo', '<p>Le mode studio de Twitch agrandit la place donnée au direct tout en gardant le chat dans la page. Il convient lorsque vous voulez suivre les deux sur un seul écran sans installer d’application.</p><p>Si vous avez besoin d’une répartition différente, placez la fenêtre du chat et celle de la vidéo côte à côte avec les fonctions de placement des fenêtres de votre système. Sur deux écrans, vous pouvez consacrer un écran au chat et l’autre à la vidéo.</p><p>Passer la vidéo seule en plein écran masque la page qui l’entoure. Pour garder le chat visible sur le même écran, revenez au mode studio ou à une disposition en fenêtres.</p>'],
      ['twichat', '3. Choisir la place du chat et de la vidéo avec Twichat', '<p>Twichat est une application gratuite pour macOS, Windows et Linux. Vous choisissez les proportions du chat et de la vidéo : un grand lecteur pour suivre le direct, plus de largeur pour les messages quand vous discutez, ou une fenêtre séparée sur un autre écran.</p><ol><li>Installez Twichat avec le guide correspondant à votre système.</li><li>Choisissez le mode anonyme pour lire, ou connectez votre compte Twitch pour écrire.</li><li>Ajoutez les chaînes que vous suivez.</li><li>Agrandissez ou réduisez le lecteur selon votre usage, ou détachez-le pour organiser les deux fenêtres séparément.</li></ol><p>Jusqu’à cent chaînes peuvent rester ouvertes, mais un seul flux vidéo est actif à la fois. Les emojis et les emotes Twitch, 7TV, BetterTTV et FrankerFaceZ sont intégrés : aucune extension à installer. Les emotes réservées aux abonnés restent soumises aux droits Twitch. Twichat reste un logiciel en alpha et ne propose pas de superposition transparente du chat par-dessus un jeu.</p>'],
      ['compte', 'Faut-il un compte pour lire ou écrire ?', '<p>Dans Twichat, le mode anonyme permet de lire les chats sans connecter de compte. Un compte Twitch est nécessaire pour envoyer des messages. Les restrictions propres à une chaîne continuent de s’appliquer, par exemple un chat réservé aux abonnés ou une vérification exigée par Twitch.</p><p>Changer de présentation ne contourne pas la modération. Si vous ne pouvez pas écrire, vérifiez d’abord votre connexion et les règles affichées par la chaîne.</p>'],
      ['mobile', 'Et sur téléphone ?', '<p>Twichat est une application de bureau : elle ne s’installe pas sur iPhone ou Android. Sur téléphone, utilisez l’application ou le site Twitch et les options de chat proposées sur votre appareil. Les étapes pour une fenêtre séparée décrites ici concernent le navigateur d’un ordinateur.</p>'],
      ['limites', 'Ce que ce guide ne couvre pas', '<p>Afficher le chat dans OBS pour les spectateurs est une autre opération : vous configurez alors la scène diffusée. Les méthodes de cette page servent à rendre le chat plus confortable sur votre propre écran. Elles n’ajoutent pas automatiquement les messages à votre diffusion.</p>']
    ] },
    en: { title: 'How to show Twitch chat in full screen', description: 'Full-screen Twitch chat, a separate window or a second monitor: choose a practical way to read messages while keeping the stream visible.', intro: 'To make Twitch chat bigger on a computer, pop it out into a separate window and maximize that window. To keep the video visible too, use Twitch Theater Mode, arrange two windows side by side or use a desktop client such as Twichat.', sections: [
      ['choose', 'Which layout fits your screen?', '<div class="reading-table"><table><thead><tr><th>What you want</th><th>Method</th><th>Keep in mind</th></tr></thead><tbody><tr><td>Read only chat in a large view</td><td>Pop-out chat window</td><td>Video stays in the channel page.</td></tr><tr><td>Keep video and chat on one screen</td><td>Theater Mode or side-by-side windows</td><td>The video player’s full-screen mode does not keep chat beside it.</td></tr><tr><td>Move chat to another monitor</td><td>Move the pop-out window</td><td>Keep video on your main screen.</td></tr><tr><td>Switch between several channels</td><td>Twichat desktop client</td><td>Several chats stay open, with one active video stream.</td></tr></tbody></table></div>'],
      ['pop-out', '1. Open Twitch chat in its own window', '<ol><li>Open a Twitch channel in a desktop browser.</li><li>In chat settings, find the option to pop out chat. Its label can vary with your Twitch language.</li><li>Maximize the new window or move it to another monitor.</li><li>Keep it in front to focus on messages. Video remains in the channel page.</li></ol><p>You can also use your browser’s full-screen mode on the chat window. This is browser full screen, not the video player’s full-screen button.</p><p>Twitch describes pop-out chat in its <a href="https://help.twitch.tv/s/article/a-tour-of-your-channel-page?language=en_US">channel page guide</a>.</p>'],
      ['video', '2. Keep chat beside the video', '<p>Twitch Theater Mode gives the stream more space while keeping chat on the page. It is a useful option when you want both on one screen without installing another application.</p><p>For a different balance, arrange the chat and video windows side by side using your operating system’s window placement controls. With two monitors, you can dedicate one to chat and the other to video.</p><p>Putting only the video in full screen hides the surrounding page. To keep chat visible on the same screen, return to Theater Mode or a windowed layout.</p>'],
      ['twichat', '3. Choose the space for chat and video with Twichat', '<p>Twichat is a free application for macOS, Windows and Linux. You choose the balance between chat and video: a big player when you want to watch, wider messages when you want to talk, or a separate window on another screen.</p><ol><li>Install Twichat using the guide for your operating system.</li><li>Choose anonymous mode to read or connect your Twitch account to write.</li><li>Add the channels you watch.</li><li>Enlarge or shrink the player to suit what you are doing, or detach it to arrange both windows separately.</li></ol><p>Up to a hundred channels can stay open, but only one video stream is active at a time. Emoji and Twitch, 7TV, BetterTTV and FrankerFaceZ emotes are built in, with no extensions to install. Subscriber emotes still require the corresponding Twitch access. Twichat is still in alpha and does not provide a transparent chat overlay over a game.</p>'],
      ['account', 'Do you need an account to read or write?', '<p>Twichat’s anonymous mode lets you read chats without connecting an account. Sending messages requires a Twitch account. Channel restrictions still apply, such as subscriber-only chat or verification required by Twitch.</p><p>A different chat layout does not bypass moderation. If you cannot write, check your sign-in status and the channel’s rules first.</p>'],
      ['mobile', 'What about phones?', '<p>Twichat is a desktop application and cannot be installed on iPhone or Android. On a phone, use the Twitch app or website and the chat options available on your device. The pop-out instructions on this page apply to desktop browsers.</p>'],
      ['limits', 'What this guide does not cover', '<p>Adding chat to OBS for your viewers is a different task: you are configuring a broadcast scene. The methods on this page make chat more comfortable on your own screen. They do not automatically add messages to your broadcast.</p>']
    ] }
  }
]

export function contentPath(entry, locale) { return `/${locale}/${entry.slugs[locale]}/` }
export function pagePath(key, locale) { return contentPath(CONTENT.find(page => page.key === key), locale) }
export const escapeHtml = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;')

export function resourceLinks(locale) {
  const fr = locale === 'fr'
  return `<nav class="resource-links" aria-label="${fr ? 'Guides et projet' : 'Guides and project'}">${[
    ['mac', 'macOS'], ['windows', 'Windows'], ['linux', 'Linux'],
    ['guide', fr ? 'Chat Twitch en plein écran' : 'Full-screen Twitch chat'],
    ['about', fr ? 'À propos et contact' : 'About and contact'], ['privacy', fr ? 'Confidentialité' : 'Privacy']
  ].map(([key, label]) => `<a href="${pagePath(key, locale)}">${label}</a>`).join('')}</nav>`
}

export function learningSection(locale) {
  const fr = locale === 'fr'
  return `<section class="learning-section" aria-labelledby="learning-title"><div><p class="eyebrow">${fr ? 'GUIDE PRATIQUE' : 'PRACTICAL GUIDE'}</p><h2 id="learning-title">${fr ? 'Chat et vidéo, à votre taille.' : 'Make room for chat and video.'}</h2><p>${fr ? 'Fenêtre séparée, mode studio, second écran : les options pour lire le chat sans perdre le direct.' : 'Pop-out chat, Theater Mode, a second monitor: ways to read chat while keeping the stream visible.'}</p><a class="learning-link" href="${pagePath('guide', locale)}">${fr ? 'Comment afficher le chat Twitch en plein écran ?' : 'How to show Twitch chat in full screen'} <span aria-hidden="true">↗</span></a></div><div class="learning-install"><h3>${fr ? 'Installer Twichat' : 'Install Twichat'}</h3><p>${fr ? 'Le bon fichier, les étapes et les réponses aux problèmes de première ouverture.' : 'The right download, installation steps and help with the first launch.'}</p>${['mac', 'windows', 'linux'].map((key, i) => `<a href="${pagePath(key, locale)}"><span>${['macOS', 'Windows', 'Linux'][i]}</span><span aria-hidden="true">→</span></a>`).join('')}</div></section>`
}

export function contentMain(entry, locale) {
  const text = entry[locale], fr = locale === 'fr'
  const install = ['mac', 'windows', 'linux'].includes(entry.key)
  const downloads = entry.key === 'linux' ? [['appimage', 'AppImage · x64'], ['appimage_arm64', 'AppImage · ARM64'], ['deb', 'deb · x64'], ['deb_arm64', 'deb · ARM64'], ['rpm', 'rpm · x64'], ['rpm_arm64', 'rpm · ARM64']] : [[entry.key, entry.key === 'mac' ? (fr ? 'macOS · DMG universel' : 'macOS · universal DMG') : 'Windows · EXE x64']]
  const picture = entry.article ? `<figure class="reading-figure"><picture><source data-shot="light" media="(prefers-color-scheme: light)" srcset="/assets/app-detached-light.${locale}.640.webp 640w, /assets/app-detached-light.${locale}.webp 1320w" sizes="(max-width: 760px) calc(100vw - 40px), 740px"><source data-shot="dark" media="(prefers-color-scheme: dark)" srcset="/assets/app-detached.${locale}.640.webp 640w, /assets/app-detached.${locale}.webp 1320w" sizes="(max-width: 760px) calc(100vw - 40px), 740px"><img src="/assets/app-detached.${locale}.webp" width="1320" height="880" loading="lazy" alt="${fr ? 'Twichat : le chat dans la fenêtre principale et le lecteur vidéo dans une fenêtre séparée.' : 'Twichat: chat in the main window and the video player in a separate window.'}"></picture><figcaption>${fr ? 'Dans Twichat, la vidéo peut avoir sa propre fenêtre.' : 'In Twichat, video can have its own window.'}</figcaption></figure>` : ''
  return `<main id="content" class="reading-page"><nav class="breadcrumbs" aria-label="${fr ? 'Fil d’Ariane' : 'Breadcrumb'}"><a href="/${locale}/">Twichat</a><span aria-hidden="true">/</span><span>${install ? (fr ? 'Installation' : 'Installation') : entry.article ? 'Guide' : fr ? 'Le projet' : 'The project'}</span></nav>
  <header class="reading-heading"><p class="eyebrow">${install ? (fr ? 'BIEN DÉMARRER' : 'GET STARTED') : entry.article ? (fr ? 'GUIDE PRATIQUE' : 'PRACTICAL GUIDE') : 'TWICHAT'}</p><h1>${escapeHtml(text.title)}</h1><p class="reading-intro">${escapeHtml(text.intro)}</p>${entry.article ? `<p class="reading-byline">${fr ? 'Par' : 'By'} <a href="${pagePath('about', locale)}">The Slumdoge Millionaire</a> · ${fr ? 'Guide pour ordinateur' : 'Desktop guide'}</p>` : ''}</header>
  <div class="reading-layout"><aside class="reading-toc"><p>${fr ? 'Sur cette page' : 'On this page'}</p><nav aria-label="${fr ? 'Sommaire' : 'Contents'}">${text.sections.map(([id, title]) => `<a href="#${id}">${escapeHtml(title)}</a>`).join('')}</nav></aside><article class="reading-body" aria-label="${escapeHtml(text.title)}">${install ? `<div class="install-downloads">${downloads.map(([platform, label]) => `<a class="button primary" href="/download?platform=${platform}&amp;lang=${locale}">${fr ? 'Télécharger' : 'Download'} ${label}</a>`).join('')}</div><p class="reading-note">${fr ? 'Application de bureau en alpha. Connexion Internet nécessaire. Aucun achat ni installation de Node.js ou de Streamlink requis.' : 'Desktop application in alpha. Internet connection required. No purchase, Node.js or Streamlink installation needed.'}</p>` : ''}${text.sections.map(([id, title, html]) => `<section id="${id}"><h2>${escapeHtml(title)}</h2>${html}${id === 'twichat' ? picture : ''}</section>`).join('')}
  <section class="reading-next"><h2>${fr ? 'Pour continuer' : 'Next steps'}</h2>${resourceLinks(locale)}<p><a href="/${locale}/">${fr ? 'Découvrir Twichat et ses captures d’écran' : 'Explore Twichat and its screenshots'}</a>${install ? ` · <a href="${repo}/releases/latest">${fr ? 'Version actuelle et sommes SHA-256' : 'Current release and SHA-256 checksums'}</a>` : ''}</p></section></article></div></main>`
}
